/* AUTO-GENERATED by sdk/dag-task-runner. Do not edit by hand — the runner overwrites this file. */
import {
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Text,
  computeDAGLayout,
  useHostTheme,
} from 'cursor/canvas';
import { useEffect, useMemo, useState } from 'react';

type TaskStatus = 'PENDING' | 'RUNNING' | 'FINISHED' | 'ERROR';
type Complexity = 'HIGH' | 'MED' | 'LOW';

interface TaskState {
  id: string;
  depends_on: string[];
  complexity: Complexity;
  subtask_prompt: string;
  status: TaskStatus;
  model: string;
  startedAt?: number;
  finishedAt?: number;
  resultText?: string;
  errorMessage?: string;
  inputTokens?: number;
  outputTokens?: number;
  durationMs?: number;
}

interface RunState {
  title: string;
  startedAt: number;
  finishedAt?: number;
  runOutcome?: 'SUCCESS' | 'FAILED' | 'INTERRUPTED';
  runMessage?: string;
  tasks: TaskState[];
}

const STATE: RunState = {
  "title": "AK System feature pipeline — smoke-test",
  "startedAt": 1778502250852,
  "tasks": [
    {
      "id": "spec",
      "depends_on": [],
      "complexity": "MED",
      "subtask_prompt": "You are the PM agent for the AK System monorepo. Read .cursor/skills/pm-agent/SKILL.md and follow it strictly.\n\nUSER REQUEST:\nSmoke test — render initial canvas only, no API calls.\n\nSlug to use for the spec filename: smoke-test\n\nDeliverable: write the spec at docs/specs/smoke-test.md following the template in your skill (Goal, User stories, Acceptance criteria, Data model, tRPC API, UI surface, Out of scope, Open questions). Reply with a one-paragraph summary and the absolute path of the spec file you wrote.",
      "status": "PENDING",
      "model": "composer-2"
    },
    {
      "id": "dev-backend",
      "depends_on": [
        "spec"
      ],
      "complexity": "HIGH",
      "subtask_prompt": "You are the dev-agent for the AK System monorepo, running as the BACKEND node. Read .cursor/skills/dev-agent/SKILL.md and follow it strictly — only touch files under packages/api/ and packages/database/.\n\nRead the spec at docs/specs/smoke-test.md end-to-end before writing any code.\n\nDeliverables, in this order:\n1. Update packages/database/src/schema.ts and schema.pg.ts with any new tables/columns the spec requires.\n2. Add or extend the tRPC router under packages/api/src/routers/<area>.ts as the spec describes. Use Zod for inputs.\n3. Register the router in packages/api/src/index.ts if it is new.\n4. Do NOT touch apps/web/ or anything under packages/types/<...>/client.\n5. End by listing every file you created or modified (absolute paths) and the names of all new tRPC procedures.",
      "status": "PENDING",
      "model": "gpt-5.3-codex"
    },
    {
      "id": "dev-frontend",
      "depends_on": [
        "spec"
      ],
      "complexity": "HIGH",
      "subtask_prompt": "You are the dev-agent for the AK System monorepo, running as the FRONTEND node. Read .cursor/skills/dev-agent/SKILL.md and follow it strictly — only touch files under apps/web/.\n\nRead the spec at docs/specs/smoke-test.md end-to-end before writing any code. Assume the backend tRPC procedures named in the spec will exist (the backend node is implementing them in parallel).\n\nDeliverables, in this order:\n1. Add or update Next.js routes under apps/web/src/app/<area>/ as the spec describes (App Router, page.tsx + layout.tsx as needed).\n2. Add shared components under apps/web/src/components/ if multiple routes need them; co-locate route-specific components inside the route folder.\n3. Wire client calls through the existing tRPC client. Do NOT inline fetch calls to /api/trpc.\n4. Style with the existing Tailwind setup. Do NOT add new CSS frameworks.\n5. End by listing every file you created or modified (absolute paths) and every new route path.",
      "status": "PENDING",
      "model": "gpt-5.3-codex"
    },
    {
      "id": "tests",
      "depends_on": [
        "dev-backend",
        "dev-frontend"
      ],
      "complexity": "MED",
      "subtask_prompt": "You are the dev-tests-agent for the AK System monorepo. Read .cursor/skills/dev-tests-agent/SKILL.md and follow it strictly.\n\nThe upstream context lists every file the dev-agent backend and frontend nodes added. The spec is at docs/specs/smoke-test.md.\n\nDeliverables:\n1. For every new tRPC procedure, add Vitest cases to (or create) packages/api/src/routers/<area>.test.ts. Cover happy path, Zod rejection, and auth gate where applicable.\n2. For every new user-facing flow, add or extend apps/web/e2e/<area>.spec.ts (Playwright). Cover the happy path from the spec acceptance criteria and one validation/error path.\n3. Do NOT modify production code. If a Playwright selector requires a data-testid that doesn't exist, leave a // TODO comment in the test instead of editing the component.\n4. Do NOT run the tests — the next DAG node does that.\n5. End by listing every test file you created or modified and the describe/test blocks you added.",
      "status": "PENDING",
      "model": "composer-2"
    },
    {
      "id": "qa",
      "depends_on": [
        "tests"
      ],
      "complexity": "MED",
      "subtask_prompt": "You are the qa-agent for the AK System monorepo. Read .cursor/skills/qa-agent/SKILL.md and follow it strictly.\n\nRun the full test suite from the repo root:\n\n  pnpm test\n  pnpm e2e\n\nIf any test fails, investigate and fix — but ONLY by editing test files or production code where the failure is unambiguously a bug introduced by the upstream dev nodes (not by your own test additions). Do not loosen assertions to make tests pass.\n\nDeliverables:\n1. Report the full test summary (pass/fail counts for unit + e2e).\n2. List every file you modified to make tests pass, with a one-line reason each.\n3. If any failure is still outstanding, mark this task ERROR and include the failing test names and the last 20 lines of output.",
      "status": "PENDING",
      "model": "composer-2"
    },
    {
      "id": "review",
      "depends_on": [
        "qa"
      ],
      "complexity": "MED",
      "subtask_prompt": "You are the reviewer-agent for the AK System monorepo. Read .cursor/skills/reviewer-agent/SKILL.md and follow it strictly.\n\nThe spec is at docs/specs/smoke-test.md. The upstream context lists every modified file and the QA test summary.\n\nDeliverables:\n1. Run pnpm -r run lint and pnpm --filter @ak-system/web build to capture static check results.\n2. Walk the diff and apply the checklist in your skill (types, Drizzle parity, tRPC Zod gates, Next.js server/client boundaries, security, performance, test coverage, style).\n3. Write the structured review to reports/smoke-test.md following the template in your skill (Verdict, Spec conformance, Static checks, Findings split by Must-fix/Should-fix/Nits, Out of scope creep, Suggested PR description).\n4. Do NOT edit production code under packages/ or apps/. The only file you may write outside reports/ is to fix obvious typos in your own review.\n5. End by replying with the verdict (APPROVED | APPROVED WITH NITS | CHANGES REQUESTED) and the absolute path to the review file.",
      "status": "PENDING",
      "model": "composer-2"
    }
  ]
};

const NODE_W = 200;
const NODE_H = 64;
const SCROLL_STORAGE_KEY = 'dag-task-runner:scroll-y';
const COMPLETED_DOT_COLOR = '#22c55e';

function pillToneFor(status: TaskStatus): 'neutral' | 'info' | 'success' | 'warning' {
  switch (status) {
    case 'PENDING':
      return 'neutral';
    case 'RUNNING':
      return 'info';
    case 'FINISHED':
      return 'success';
    case 'ERROR':
      return 'warning';
  }
}

function complexityTone(c: Complexity): 'neutral' | 'info' | 'warning' {
  switch (c) {
    case 'HIGH':
      return 'warning';
    case 'MED':
      return 'info';
    case 'LOW':
      return 'neutral';
  }
}

function formatDuration(ms?: number): string {
  if (ms === undefined) return '—';
  if (ms < 1000) return ms + 'ms';
  const s = ms / 1000;
  if (s < 60) return s.toFixed(1) + 's';
  const m = Math.floor(s / 60);
  const rem = Math.round(s - m * 60);
  return m + 'm ' + rem + 's';
}

function elapsed(state: RunState): number {
  const end = state.finishedAt ?? Date.now();
  return end - state.startedAt;
}

function totalTokens(state: RunState): { input: number; output: number } {
  let input = 0;
  let output = 0;
  for (const t of state.tasks) {
    input += t.inputTokens ?? 0;
    output += t.outputTokens ?? 0;
  }
  return { input, output };
}

function taskElementId(taskId: string): string {
  return 'task-card-' + taskId;
}

function getScrollY(): number {
  if (typeof window === 'undefined') return 0;
  return Math.max(window.scrollY ?? 0, 0);
}

function saveScrollY(): void {
  if (typeof window === 'undefined') return;
  try {
    window.sessionStorage.setItem(SCROLL_STORAGE_KEY, String(getScrollY()));
  } catch {
    // ignore storage failures
  }
}

function restoreScrollY(): void {
  if (typeof window === 'undefined') return;
  let target = 0;
  try {
    const raw = window.sessionStorage.getItem(SCROLL_STORAGE_KEY);
    if (!raw) return;
    const parsed = Number(raw);
    if (!Number.isFinite(parsed) || parsed <= 0) return;
    target = Math.floor(parsed);
  } catch {
    return;
  }

  // Retry because hot-reload can run before content height has settled.
  let attempts = 0;
  const maxAttempts = 8;
  const tick = (): void => {
    attempts += 1;
    const scrollHeight = Math.max(
      document.documentElement?.scrollHeight ?? 0,
      document.body?.scrollHeight ?? 0,
    );
    const maxY = Math.max(scrollHeight - window.innerHeight, 0);
    if (maxY <= 0) {
      if (attempts < maxAttempts) window.requestAnimationFrame(tick);
      return;
    }
    const desiredY = Math.min(target, maxY);
    window.scrollTo({ top: desiredY, behavior: 'auto' });
    if (attempts < maxAttempts && Math.abs(getScrollY() - desiredY) > 2) {
      window.requestAnimationFrame(tick);
    }
  };
  window.requestAnimationFrame(tick);
}

function DAGGraph({
  state,
  onNodeClick,
}: {
  state: RunState;
  onNodeClick?: (taskId: string) => void;
}): JSX.Element {
  const theme = useHostTheme();
  const layout = computeDAGLayout({
    nodes: state.tasks.map((t) => ({ id: t.id })),
    edges: state.tasks.flatMap((t) =>
      t.depends_on.map((d) => ({ from: d, to: t.id })),
    ),
    direction: 'vertical',
    nodeWidth: NODE_W,
    nodeHeight: NODE_H,
    rankGap: 72,
    nodeGap: 40,
    padding: 24,
  });

  const byId = new Map(state.tasks.map((t) => [t.id, t]));

  function nodeFill(status: TaskStatus): string {
    switch (status) {
      case 'PENDING':
        return theme.fill.tertiary;
      case 'RUNNING':
        return theme.fill.secondary;
      case 'FINISHED':
        return theme.fill.secondary;
      case 'ERROR':
        return theme.fill.secondary;
    }
  }

  function nodeStroke(status: TaskStatus): string {
    switch (status) {
      case 'PENDING':
        return theme.stroke.tertiary;
      case 'RUNNING':
        return theme.accent.primary;
      case 'FINISHED':
        return COMPLETED_DOT_COLOR;
      case 'ERROR':
        return theme.stroke.primary;
    }
  }

  function statusGlyph(status: TaskStatus): string {
    switch (status) {
      case 'PENDING':
        return '○';
      case 'RUNNING':
        return '◐';
      case 'FINISHED':
        return '●';
      case 'ERROR':
        return '×';
    }
  }

  function statusGlyphColor(status: TaskStatus): string {
    switch (status) {
      case 'PENDING':
        return theme.text.tertiary;
      case 'RUNNING':
        return theme.accent.primary;
      case 'FINISHED':
        return COMPLETED_DOT_COLOR;
      case 'ERROR':
        return theme.text.primary;
    }
  }

  return (
    <svg
      width={layout.width}
      height={layout.height}
      style={{ display: 'block', maxWidth: '100%' }}
    >
      <defs>
        <marker
          id="dag-arrow"
          viewBox="0 0 10 10"
          refX="9"
          refY="5"
          markerWidth="6"
          markerHeight="6"
          orient="auto-start-reverse"
        >
          <path d="M 0 0 L 10 5 L 0 10 z" fill={theme.stroke.secondary} />
        </marker>
      </defs>
      {layout.edges.map((e, i) => (
        <line
          key={'e' + i}
          x1={e.sourceX}
          y1={e.sourceY}
          x2={e.targetX}
          y2={e.targetY}
          stroke={theme.stroke.secondary}
          strokeWidth={1.25}
          strokeDasharray={e.isBackEdge ? '4 3' : undefined}
          markerEnd="url(#dag-arrow)"
        />
      ))}
      {layout.nodes.map((n) => {
        const t = byId.get(n.id);
        if (!t) return null;
        return (
          <g
            key={n.id}
            transform={'translate(' + n.x + ',' + n.y + ')'}
            onClick={() => onNodeClick?.(n.id)}
            style={{ cursor: onNodeClick ? 'pointer' : 'default' }}
          >
            <rect
              width={NODE_W}
              height={NODE_H}
              rx={8}
              ry={8}
              fill={nodeFill(t.status)}
              stroke={nodeStroke(t.status)}
              strokeWidth={t.status === 'RUNNING' ? 2 : 1}
            />
            <text
              x={12}
              y={22}
              fontSize={11}
              fontFamily="ui-monospace, SFMono-Regular, Menlo, monospace"
              fill={statusGlyphColor(t.status)}
            >
              {statusGlyph(t.status)}
            </text>
            <text
              x={28}
              y={22}
              fontSize={13}
              fontWeight={600}
              fill={theme.text.primary}
            >
              {t.id.length > 22 ? t.id.slice(0, 21) + '…' : t.id}
            </text>
            <text
              x={12}
              y={42}
              fontSize={10.5}
              fill={theme.text.secondary}
            >
              {t.complexity} · {t.model}
            </text>
            <text
              x={12}
              y={58}
              fontSize={10.5}
              fill={theme.text.tertiary}
            >
              {t.status === 'FINISHED' || t.status === 'ERROR'
                ? formatDuration(t.durationMs)
                : t.status === 'RUNNING'
                  ? 'running…'
                  : 'pending'}
            </text>
          </g>
        );
      })}
    </svg>
  );
}

function TaskList({
  state,
  forcedOpenVersionByTaskId,
}: {
  state: RunState;
  forcedOpenVersionByTaskId: Record<string, number>;
}): JSX.Element {
  const theme = useHostTheme();
  return (
    <Stack gap={10}>
      {state.tasks.map((t) => {
        const trailing = (
          <Row gap={6} align="center">
            <Pill tone={complexityTone(t.complexity)} size="sm">
              {t.complexity}
            </Pill>
            <Pill tone={pillToneFor(t.status)} active={t.status !== 'PENDING'} size="sm">
              {t.status}
            </Pill>
          </Row>
        );
        return (
          <div key={t.id} id={taskElementId(t.id)}>
            <Card
              key={t.id + ':' + String(forcedOpenVersionByTaskId[t.id] ?? 0)}
              collapsible
              defaultOpen={t.status !== 'PENDING' || (forcedOpenVersionByTaskId[t.id] ?? 0) > 0}
            >
            <CardHeader trailing={trailing}>{t.id}</CardHeader>
            <CardBody>
              <Stack gap={8}>
                <Text tone="secondary" size="small">
                  Model {t.model}
                  {t.depends_on.length > 0 ? ' · depends on ' + t.depends_on.join(', ') : ''}
                  {t.durationMs !== undefined ? ' · ' + formatDuration(t.durationMs) : ''}
                  {t.inputTokens !== undefined || t.outputTokens !== undefined
                    ? ' · ' + (t.inputTokens ?? 0) + ' in / ' + (t.outputTokens ?? 0) + ' out tokens'
                    : ''}
                </Text>
                <Text size="small">
                  <Text as="span" weight="semibold">Prompt: </Text>
                  {t.subtask_prompt}
                </Text>
                {t.resultText ? (
                  <Stack gap={4}>
                    <Text size="small" weight="semibold">
                      {t.status === 'RUNNING' ? 'Streaming output' : 'Result'}
                    </Text>
                    <pre
                      style={{
                        margin: 0,
                        padding: 10,
                        borderRadius: 6,
                        background: theme.bg.elevated,
                        border: '1px solid ' + theme.stroke.tertiary,
                        color: theme.text.secondary,
                        fontSize: 12,
                        lineHeight: 1.45,
                        fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
                        whiteSpace: 'pre-wrap',
                        wordBreak: 'break-word',
                        maxHeight: 320,
                        overflow: 'auto',
                      }}
                    >
                      {t.resultText}
                      {t.status === 'RUNNING' ? '\u2588' : ''}
                    </pre>
                  </Stack>
                ) : t.status === 'RUNNING' ? (
                  <Text size="small" tone="tertiary" italic>
                    Waiting for first token…
                  </Text>
                ) : null}
                {t.errorMessage ? (
                  <Stack gap={4}>
                    <Text size="small" weight="semibold">Error</Text>
                    <Text size="small" tone="secondary">{t.errorMessage}</Text>
                  </Stack>
                ) : null}
              </Stack>
            </CardBody>
            </Card>
          </div>
        );
      })}
    </Stack>
  );
}

export default function DagRun(): JSX.Element {
  const [forcedOpenVersionByTaskId, setForcedOpenVersionByTaskId] = useState<Record<string, number>>({});
  const taskIds = useMemo(() => new Set(STATE.tasks.map((t) => t.id)), []);

  useEffect(() => {
    restoreScrollY();
    const onScroll = (): void => saveScrollY();
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => {
      saveScrollY();
      window.removeEventListener('scroll', onScroll);
    };
  }, []);

  const handleNodeClick = (taskId: string): void => {
    if (!taskIds.has(taskId)) return;

    setForcedOpenVersionByTaskId((prev) => ({
      ...prev,
      [taskId]: (prev[taskId] ?? 0) + 1,
    }));

    const targetId = taskElementId(taskId);
    const scrollToTask = (): void => {
      const el = document.getElementById(targetId);
      if (!el) return;
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    };

    // Wait one frame so the forced-open remount lands before we scroll.
    window.requestAnimationFrame(scrollToTask);
  };

  const counts = STATE.tasks.reduce(
    (acc, t) => {
      acc.total += 1;
      acc[t.status.toLowerCase() as 'pending' | 'running' | 'finished' | 'error'] += 1;
      return acc;
    },
    { total: 0, pending: 0, running: 0, finished: 0, error: 0 },
  );
  const tokens = totalTokens(STATE);
  const isFinal = STATE.finishedAt !== undefined;
  const statusLabel =
    STATE.runOutcome === 'INTERRUPTED'
      ? 'INTERRUPTED'
      : STATE.runOutcome === 'FAILED'
        ? 'FAILED'
        : isFinal
          ? 'COMPLETE'
          : 'RUNNING';
  const statusTone =
    STATE.runOutcome === 'INTERRUPTED' || STATE.runOutcome === 'FAILED'
      ? 'danger'
      : isFinal
        ? 'success'
        : 'info';

  return (
    <Stack gap={20}>
      <Stack gap={6}>
        <H1>{STATE.title}</H1>
        <Row gap={10} align="center">
          <Pill tone={statusTone} active size="sm">
            {statusLabel}
          </Pill>
          <Text tone="secondary" size="small">
            {counts.total} tasks · elapsed {formatDuration(elapsed(STATE))}
            {tokens.input + tokens.output > 0
              ? ' · ' + tokens.input + ' in / ' + tokens.output + ' out tokens'
              : ''}
          </Text>
        </Row>
        {STATE.runMessage ? (
          <Text tone="secondary" size="small">
            {STATE.runMessage}
          </Text>
        ) : null}
      </Stack>

      <Grid columns={5} gap={12}>
        <Stat value={String(counts.total)} label="Total" />
        <Stat value={String(counts.pending)} label="Pending" />
        <Stat value={String(counts.running)} label="Running" tone={counts.running > 0 ? 'info' : undefined} />
        <Stat value={String(counts.finished)} label="Finished" tone={counts.finished > 0 ? 'success' : undefined} />
        <Stat value={String(counts.error)} label="Errored" tone={counts.error > 0 ? 'danger' : undefined} />
      </Grid>

      <Divider />

      <Stack gap={12}>
        <H2>Graph</H2>
        <DAGGraph state={STATE} onNodeClick={handleNodeClick} />
      </Stack>

      <Divider />

      <Stack gap={12}>
        <H2>Tasks</H2>
        <TaskList state={STATE} forcedOpenVersionByTaskId={forcedOpenVersionByTaskId} />
      </Stack>
    </Stack>
  );
}
