#!/usr/bin/env bash
# Enable WhatsApp bridge on EC2: create whatsapp-bridge.env, start docker profile, print pairing steps.
# Usage: pnpm ec2:whatsapp   (or bash scripts/ec2-whatsapp-setup.sh)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

EC2_ENV="$ROOT_DIR/deploy/ec2.env"
PROD_ENV="$ROOT_DIR/deploy/production.env"
BRIDGE_ENV="$ROOT_DIR/deploy/whatsapp-bridge.env"
COMPOSE_FILE="deploy/docker-compose.production.yml"

for f in "$EC2_ENV" "$PROD_ENV"; do
  if [ ! -f "$f" ]; then
    echo "✗  Missing $f"
    exit 1
  fi
done

set -a
# shellcheck disable=SC1090
source "$EC2_ENV"
source "$PROD_ENV"
set +a

: "${DEPLOY_HOST:?}"
: "${WHATSAPP_BRIDGE_SECRET:?set WHATSAPP_BRIDGE_SECRET in deploy/production.env}"

APP_URL="${APP_URL:-${NEXT_PUBLIC_APP_URL:-}}"
if [ -z "$APP_URL" ] || [[ "$APP_URL" == *your-domain* ]]; then
  echo "✗  Set APP_URL in deploy/ec2.env or NEXT_PUBLIC_APP_URL in deploy/production.env"
  exit 1
fi

SSH_OPTS=(-o StrictHostKeyChecking=accept-new)
[ -n "${SSH_KEY:-}" ] && SSH_OPTS+=(-i "${SSH_KEY/#\~/$HOME}")
REMOTE="${DEPLOY_USER:-ubuntu}@${DEPLOY_HOST}"

echo "━━ Generate deploy/whatsapp-bridge.env ━━"
cat > "$BRIDGE_ENV" <<EOF
# Auto-generated by scripts/ec2-whatsapp-setup.sh — do not commit
PORT=3001
AUTH_STATE_PATH=/data/auth
BRIDGE_SECRET=${WHATSAPP_BRIDGE_SECRET}
AK_WEBHOOK_URL=${APP_URL}/api/whatsapp/webhook
AK_GROUP_SUMMARY_URL=${APP_URL}/api/whatsapp/group-summary
REPLY_ENABLED=1
DEVICE_NAME=AK System
SELF_JID=${WHATSAPP_ALLOWED_JID:-}
SELF_LID=${WHATSAPP_ALLOWED_LID:-}
EOF
echo "✓  $BRIDGE_ENV"

echo ""
echo "━━ Sync + start whatsapp profile on EC2 ━━"
scp "${SSH_OPTS[@]}" "$BRIDGE_ENV" "${REMOTE}:${DEPLOY_PATH:-/opt/ak-system}/deploy/whatsapp-bridge.env"
ssh "${SSH_OPTS[@]}" "$REMOTE" \
  "cd '${DEPLOY_PATH:-/opt/ak-system}' && docker compose -f '$COMPOSE_FILE' --profile whatsapp up -d --build"

echo ""
echo "━━ Bridge status ━━"
sleep 3
ssh "${SSH_OPTS[@]}" "$REMOTE" \
  "curl -sf http://127.0.0.1:3001/health && echo '' && docker compose -f '${DEPLOY_PATH:-/opt/ak-system}/$COMPOSE_FILE' ps" || true

echo ""
echo "════════════════════════════════════════════════════════════"
echo "✓  WhatsApp bridge is starting on EC2"
echo ""
echo "Pair (QR) — run on your Mac in a new terminal:"
echo "  pnpm ec2:whatsapp:pair"
echo ""
echo "Or manually:"
echo "  ssh -L 3001:127.0.0.1:3001 -i ~/.ssh/ak-system.pem ubuntu@${DEPLOY_HOST}"
echo "  open http://localhost:3001"
echo ""
echo "After scan: Settings → WhatsApp → copy self JID → add WHATSAPP_ALLOWED_JID to production.env → redeploy"
echo "════════════════════════════════════════════════════════════"
