#!/usr/bin/env bash
# Install (or reinstall) the Outlook → Google Dragontail bridge as a launchd agent.
# Runs the bridge every 15 minutes while this Mac is awake.
#
# launchd cannot read Google Drive directly. The plist invokes osascript so the
# bridge runs in the logged-in user session (same TCC context as Terminal).
#
#   bash scripts/install-outlook-bridge.sh            # install + load
#   bash scripts/install-outlook-bridge.sh --uninstall # unload + remove
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

LABEL="com.ak.outlook-bridge"
TEMPLATE="$ROOT_DIR/deploy/launchd/${LABEL}.plist"
AGENTS_DIR="$HOME/Library/LaunchAgents"
TARGET="$AGENTS_DIR/${LABEL}.plist"
LOCAL_DIR="$HOME/.ak-system"
LOCAL_RUNNER="$LOCAL_DIR/outlook-bridge-run.sh"
LOCAL_ENV="$LOCAL_DIR/outlook-bridge.env"
LOCAL_LOG="$LOCAL_DIR/outlook-bridge.log"
LOCAL_HELPER="$LOCAL_DIR/calendar-helper"
REPO_RUNNER="$ROOT_DIR/scripts/outlook-bridge-run.sh"
REPO_ENV="$ROOT_DIR/apps/web/.env.local"

if [ "$(uname)" != "Darwin" ]; then
  echo "✗  The Outlook bridge only runs on macOS."
  exit 1
fi

uninstall() {
  launchctl bootout "gui/$(id -u)/${LABEL}" 2>/dev/null || launchctl unload "$TARGET" 2>/dev/null || true
  rm -f "$TARGET" "$LOCAL_RUNNER" "$LOCAL_ENV" "$LOCAL_HELPER"
  echo "✓  Uninstalled ${LABEL}."
}

if [ "${1:-}" = "--uninstall" ]; then
  uninstall
  exit 0
fi

[ -f "$TEMPLATE" ] || { echo "✗  Missing template $TEMPLATE"; exit 1; }
[ -f "$REPO_RUNNER" ] || { echo "✗  Missing runner $REPO_RUNNER"; exit 1; }
[ -f "$REPO_ENV" ] || { echo "✗  Missing $REPO_ENV — create it from .env.local.example first"; exit 1; }

mkdir -p "$AGENTS_DIR" "$LOCAL_DIR"

HELPER_SRC="$ROOT_DIR/packages/api/src/services/calendar-helper/calendar-helper"
[ -f "$HELPER_SRC" ] || { echo "✗  Missing $HELPER_SRC"; exit 1; }
cp -f "$HELPER_SRC" "$LOCAL_HELPER"
chmod +x "$LOCAL_HELPER"

# Copy bridge-related env vars to a local path launchd can read.
# Prefer deploy/production.env Google credentials (same OAuth client as tunnel/production).
PROD_ENV="$ROOT_DIR/deploy/production.env"
GOOGLE_ENV_SOURCE="$REPO_ENV"
if [ -f "$PROD_ENV" ] && grep -q '^GOOGLE_CLIENT_ID=' "$PROD_ENV"; then
  GOOGLE_ENV_SOURCE="$PROD_ENV"
fi
{
  echo "# Generated $(date -u '+%Y-%m-%dT%H:%M:%SZ') from ${GOOGLE_ENV_SOURCE##*/} + apps/web/.env.local"
  echo "# Re-run install-outlook-bridge.sh after changing Google OAuth credentials."
  grep -E '^(GOOGLE_CLIENT_ID|GOOGLE_CLIENT_SECRET|GOOGLE_CALENDAR_CLIENT_ID|GOOGLE_CALENDAR_CLIENT_SECRET)=' "$GOOGLE_ENV_SOURCE" 2>/dev/null || true
  grep -E '^(DRAGONTAIL_|OUTLOOK_|TIMEZONE=)' "$REPO_ENV" || true
  echo "DATABASE_PATH=\"${ROOT_DIR}/apps/web/data/ak_system.sqlite\""
  echo "CALENDAR_HELPER_PATH=\"${LOCAL_HELPER}\""
  echo "OUTLOOK_BRIDGE_HELPER_TIMEOUT_MS=120000"
} > "$LOCAL_ENV"
chmod 600 "$LOCAL_ENV"

cat > "$LOCAL_RUNNER" <<EOF
#!/usr/bin/env bash
# Generated by scripts/install-outlook-bridge.sh — do not edit by hand.
set -euo pipefail

ROOT_DIR="${ROOT_DIR}"
ENV_FILE="${LOCAL_ENV}"
LOG_FILE="${LOCAL_LOG}"
BRIDGE_SCRIPT="\${ROOT_DIR}/scripts/outlook-to-google-sync.ts"

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\${PATH}"
if command -v corepack >/dev/null 2>&1; then corepack enable >/dev/null 2>&1 || true; fi

if [ -f "\$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  source "\$ENV_FILE"
  set +a
fi

export DATABASE_PATH="\${ROOT_DIR}/apps/web/data/ak_system.sqlite"

{
  echo "──────── \$(date '+%Y-%m-%d %H:%M:%S') ────────"
  cd "\$ROOT_DIR"
  # Prevent overlapping runs (launchd + manual) from creating duplicate Google events.
  LOCK_DIR="\${HOME}/.ak-system/outlook-bridge.lock.d"
  if ! mkdir "\$LOCK_DIR" 2>/dev/null; then
    echo "[outlook-bridge] skipped — another run is in progress"
    exit 0
  fi
  trap 'rmdir "\$LOCK_DIR" 2>/dev/null || true' EXIT
  pnpm exec tsx "\$BRIDGE_SCRIPT"
} >> "\$LOG_FILE" 2>&1
EOF
chmod +x "$LOCAL_RUNNER"

sed \
  -e "s|__RUN_SCRIPT__|${LOCAL_RUNNER}|g" \
  -e "s|__WORKDIR__|${LOCAL_DIR}|g" \
  -e "s|__LOG__|${LOCAL_LOG}|g" \
  "$TEMPLATE" > "$TARGET"

launchctl bootout "gui/$(id -u)/${LABEL}" 2>/dev/null || launchctl unload "$TARGET" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$TARGET" 2>/dev/null || launchctl load "$TARGET"

echo "✓  Installed and loaded ${LABEL}."
echo "   Local runner: $LOCAL_RUNNER"
echo "   Local env:    $LOCAL_ENV"
echo "   Repo runner:  $REPO_RUNNER (manual runs from Terminal)"
echo "   Log:          $LOCAL_LOG"
echo "   Runs every 900s while the Mac is awake (RunAtLoad triggers one now)."
echo "   Re-run this script after changing apps/web/.env.local OAuth settings."
echo "   Status: launchctl list | grep ${LABEL}"
echo "   Stop:   bash scripts/install-outlook-bridge.sh --uninstall"
